In [44]:
import numpy as np

In [66]:
class LinSystem():
    matrix = None
    vector = None
    
    def __init__(self,M,V):
        self.matrix = M
        self.vector = V
        
    def Jacobi(self,itmax=1000,error = 1e-10):
        A = self.matrix
        b = self.vector
        
        M,N = A.shape
    
        x = np.zeros(N)

        sumk = np.zeros_like(x)

        x = [13,20,-1]

        it = 0

        residuo = np.linalg.norm( b - np.dot(A,x) )

        while ( residuo > error and it < itmax ):

            it += 1

            for i in range(M):
                sum_ = 0
                for j in range(N):
                    if i != j:
                        sum_ += A[i][j]*x[j]
                sumk[i] = sum_

            for i in range(M):

                if A[i,i] != 0:
                    x[i] = (b[i] - sumk[i])/A[i,i]
                else:
                    print('No invertible con Jacobi')

            residuo = np.linalg.norm( b - np.dot(A,x) )
            
        print("Se resolvió el sistema con un total de ", it, " iteraciones.")

        return x,residuo
    
    def GausSeidel(self,itmax=1000,error = 1e-10):
        A = self.matrix
        b = self.vector
        
        M,N = A.shape
    
        x = np.zeros(N)

        sumk = np.zeros_like(x)
        
        it = 0

        residuo = np.linalg.norm( b - np.dot(A,x) )

        while ( residuo > error and it < itmax ):

            it += 1

            for i in range(M):
                if i == 0:
                    sumk[i] = (1 + sumk[1] + sumk[2])/3
                elif i == 1:
                    sumk[i] = (3 + sumk[0] - sumk[2])/3
                elif i == 2:
                    sumk[i] = (7 - 2*sumk[0] - sumk[1])/4

            for i in range(M):

                if A[i,i] != 0:
                    x[i] = (b[i] - sumk[i])/A[i,i]
                else:
                    print('No invertible con GausSeidel')

            residuo = np.linalg.norm( b - np.dot(A,x) )
            
        print("Se resolvió el sistema con un total de ", it, " iteraciones.")

        return x,residuo
        

In [67]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [68]:
sis = LinSystem(M,b)

In [69]:
X,error = sis.Jacobi()

Se resolvió el sistema con un total de  26  iteraciones.


In [70]:
X

[1.0000000000012628, 1.0000000000109328, 0.9999999999902489]

In [71]:
Xs,errors = sis.GausSeidel()

Se resolvió el sistema con un total de  1000  iteraciones.


In [72]:
Xs

array([0.        , 0.66666667, 1.5       ])