In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
b = np.array([[-3],[-3],[8],[9]])
u1 = np.array([[3],[1],[0],[1]])
u2 = np.array([[1],[2],[1],[1]])
u3 = np.array([[-1],[0],[2],[-1]])

In [3]:
b

array([[-3],
       [-3],
       [ 8],
       [ 9]])

In [4]:
u1

array([[3],
       [1],
       [0],
       [1]])

In [5]:
u2

array([[1],
       [2],
       [1],
       [1]])

In [6]:
u3

array([[-1],
       [ 0],
       [ 2],
       [-1]])

In [7]:
A = np.zeros((4,3))
A[:,0] = u1[:,0]
A[:,1] = u2[:,0]
A[:,2] = u3[:,0]

In [8]:
A

array([[ 3.,  1., -1.],
       [ 1.,  2.,  0.],
       [ 0.,  1.,  2.],
       [ 1.,  1., -1.]])

## a) MÍNIMOS CUADRADOS

In [9]:
def minCuad(A,B):
    m,n = A.shape
   
    AtA = np.dot(A.T,A)
    
    AtB = np.dot(A.T,B)
    
    X = np.linalg.solve(AtA,AtB)
    
    D = np.dot(A,X)-B
    
    return X,D

In [10]:
X,_ = minCuad(A,b)

## Resultado sin redondear

In [11]:
p1b = np.dot(A,X)
p1b

array([[-2.0000000e+00],
       [ 3.0000000e+00],
       [ 4.0000000e+00],
       [-4.4408921e-16]])

## Resultado redondeado

In [12]:
rp1b = np.round(p1b,0)
rp1b

array([[-2.],
       [ 3.],
       [ 4.],
       [-0.]])

## b) GRAND-SCHMIDT

In [13]:
def GrandSchmidt(W,b):
    m,n = W.shape
    
    V = np.zeros((m,n))
    
    for j in range(n):
        e = W[:,j]
        norm = np.linalg.norm(e)
        v = e/norm
        
        for i in range(m):
            V[i,j] = v[i]
            
    C = np.zeros((n))
    
    for i in range(n):
        v = V[:,i]
        C[i] = np.dot(b.T,v) 
        
    pb = C[0]*V[:,0] + C[1]*V[:,1] + C[2]*V[:,2]
    
    return pb
    

In [14]:
p2b = GrandSchmidt(A,b)

In [15]:
p2b

array([-1.34199134,  2.01298701,  4.47619048, -0.7965368 ])